In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [5]:
inputs = df.drop(['Survived'],axis='columns')
target = df['Survived']


In [6]:
dummies = pd.get_dummies(inputs.Sex)
dummies

female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[891 rows x 2 columns]

In [7]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [8]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [9]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [13]:
inputs.Age = inputs.Age.fillna(inputs.Age.median())
inputs.head(6)

Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False
5       3  28.0   8.4583   False

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [15]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [16]:
model.fit(X_train,y_train)

GaussianNB()

In [17]:
model.score(X_test,y_test)

0.7723880597014925

In [18]:
X_test[0:10]

Pclass   Age     Fare  female
592       3  47.0   7.2500   False
675       3  18.0   7.7750   False
759       1  33.0  86.5000    True
786       3  18.0   7.4958    True
782       1  29.0  30.0000   False
125       3  12.0  11.2417   False
399       2  28.0  12.6500    True
744       3  31.0   7.9250   False
361       2  29.0  27.7208   False
193       2   3.0  26.0000   False

In [19]:
y_test[0:10]

592    0
675    0
759    1
786    1
782    0
125    1
399    1
744    1
361    0
193    1
Name: Survived, dtype: int64

In [20]:
model.predict(X_test[0:10])

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0])

In [21]:
model.predict_proba(X_test[:10])

array([[0.96900111, 0.03099889],
       [0.95599248, 0.04400752],
       [0.01205642, 0.98794358],
       [0.33241678, 0.66758322],
       [0.73649025, 0.26350975],
       [0.9482163 , 0.0517837 ],
       [0.22351834, 0.77648166],
       [0.96603446, 0.03396554],
       [0.92282814, 0.07717186],
       [0.85025045, 0.14974955]])

In [22]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.752     , 0.832     , 0.784     , 0.76612903, 0.73387097])

In [27]:
naive_score = cross_val_score(GaussianNB(),X_train, y_train, cv=5)
print(naive_score)

[0.752      0.832      0.784      0.76612903 0.73387097]


In [28]:
np.average(naive_score)

np.float64(0.7736000000000001)

In [29]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [32]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [67]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [68]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.Message,
    df.spam,
    test_size=0.3,
    random_state=42
)


In [69]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_train_count = v.fit_transform(X_train)


In [70]:
X_test_count = v.transform(X_test)


In [71]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

In [72]:
y_pred = model.predict(X_test_count)


In [73]:
model.score(X_test_count,y_test)

0.9904306220095693

In [74]:
X_test

3245    Squeeeeeze!! This is christmas hug.. If u lik ...
944     And also I've sorta blown him off a couple tim...
1044    Mmm thats better now i got a roast down me! i’...
2484        Mm have some kanji dont eat anything heavy ok
812     So there's a ring that comes with the guys cos...
                              ...                        
2505    Hello, my boytoy! I made it home and my consta...
2525    FREE entry into our £250 weekly comp just send...
4975    Aiyo u so poor thing... Then u dun wan 2 eat? ...
650     You have won ?1,000 cash or a ?2,000 prize! To...
4463    Sorry I flaked last night, shit's seriously go...
Name: Message, Length: 1672, dtype: object

In [75]:
y_test

3245    0
944     0
1044    0
2484    0
812     0
       ..
2505    0
2525    1
4975    0
650     1
4463    0
Name: spam, Length: 1672, dtype: int64

USING SKLEARN PIPELINE

In [76]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [77]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [78]:
clf.score(X_test,y_test)

0.9904306220095693

In [81]:
clf.predict(X_test[:50])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0])

EXERCISE

In [82]:
from sklearn.datasets import load_wine
wines = load_wine()

In [85]:
print(wines)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]], shape=(178, 13)), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [86]:
dir(wines)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [89]:
wines.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [102]:
df = pd.DataFrame(wines.data,columns=wines.feature_names)
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [103]:
df.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  
count       178.000000  178.000000                    178.000000   178.000000  
mean          5.058090    0.957449                      2.611685   746.893258  
std           2.318286    0.228572                      0.709990   314.907474  
min           1.280000    0.480000                      1.270000   278.000000  
25%           3.220000    0.782500                      1.937500   500.500000  
50%           4.690000    0.965000                      2.780000   673.500000  
75%           6.200000    1.120000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1680.000000

In [108]:
df.isna().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

In [109]:
df['target'] = wines.target
df[50:70]

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
50    13.05        1.73  2.04               12.4       92.0           2.72   
51    13.83        1.65  2.60               17.2       94.0           2.45   
52    13.82        1.75  2.42               14.0      111.0           3.88   
53    13.77        1.90  2.68               17.1      115.0           3.00   
54    13.74        1.67  2.25               16.4      118.0           2.60   
55    13.56        1.73  2.46               20.5      116.0           2.96   
56    14.22        1.70  2.30               16.3      118.0           3.20   
57    13.29        1.97  2.68               16.8      102.0           3.00   
58    13.72        1.43  2.50               16.7      108.0           3.40   
59    12.37        0.94  1.36               10.6       88.0           1.98   
60    12.33        1.10  2.28               16.0      101.0           2.05   
61    12.64        1.36  2.02               16.8      100.0           2.02   
62    13.67        1.25  1.92               18.0       94.0           2.10   
63    12.37        1.13  2.16               19.0       87.0           3.50   
64    12.17        1.45  2.53               19.0      104.0           1.89   
65    12.37        1.21  2.56               18.1       98.0           2.42   
66    13.11        1.01  1.70               15.0       78.0           2.98   
67    12.37        1.17  1.92               19.6       78.0           2.11   
68    13.34        0.94  2.36               17.0      110.0           2.53   
69    12.21        1.19  1.75               16.8      151.0           1.85   

    flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
50        3.27                  0.17             2.91             7.20  1.12   
51        2.99                  0.22             2.29             5.60  1.24   
52        3.74                  0.32             1.87             7.05  1.01   
53        2.79                  0.39             1.68             6.30  1.13   
54        2.90                  0.21             1.62             5.85  0.92   
55        2.78                  0.20             2.45             6.25  0.98   
56        3.00                  0.26             2.03             6.38  0.94   
57        3.23                  0.31             1.66             6.00  1.07   
58        3.67                  0.19             2.04             6.80  0.89   
59        0.57                  0.28             0.42             1.95  1.05   
60        1.09                  0.63             0.41             3.27  1.25   
61        1.41                  0.53             0.62             5.75  0.98   
62        1.79                  0.32             0.73             3.80  1.23   
63        3.10                  0.19             1.87             4.45  1.22   
64        1.75                  0.45             1.03             2.95  1.45   
65        2.65                  0.37             2.08             4.60  1.19   
66        3.18                  0.26             2.28             5.30  1.12   
67        2.00                  0.27             1.04             4.68  1.12   
68        1.30                  0.55             0.42             3.17  1.02   
69        1.28                  0.14             2.50             2.85  1.28   

    od280/od315_of_diluted_wines  proline  target  
50                          2.91   1150.0       0  
51                          3.37   1265.0       0  
52                          3.26   1190.0       0  
53                          2.93   1375.0       0  
54                          3.20   1060.0       0  
55                          3.03   1120.0       0  
56                          3.31    970.0       0  
57                          2.84   1270.0       0  
58                          2.87   1285.0       0  
59                          1.82    520.0       1  
60                          1.67    680.0       1  
61                          1.59    450.0       1  
62      

In [110]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(wines.data, wines.target, test_size=0.3, random_state=100)

In [111]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [112]:
model.score(X_test,y_test)

1.0

In [113]:
mn = MultinomialNB()
mn.fit(X_train,y_train)
mn.score(X_test,y_test)

0.7777777777777778