<h2 align="center" style="color:blue">Codebasics Course: Numpy Slicing, Stacking </h2>

In [1]:
import numpy as np

### Indexing, Slicing

In [2]:
a = np.array([6,7,8,9])
a[0:2]

array([6, 7])

In [3]:
a[2:]

array([8, 9])

In [4]:
a[-1]

np.int64(9)

In [5]:
a[-2:]

array([8, 9])

In [6]:
b = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

In [7]:
b[1,2]

np.int64(6)

In [8]:
b[2,0]

np.int64(7)

In [9]:
b[0:2,2]

array([3, 6])

In [10]:
b[-1]

array([7, 8, 9])

In [11]:
b[-1, 0:2]

array([7, 8])

In [12]:
b[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

### vstack, hstack

In [13]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [14]:
np.hstack((c, d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [15]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [16]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])

In [17]:
f = np.vstack((c,e))
f

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

### vsplit, hsplit

In [18]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

np.hsplit(transactions, [3])

[array([['101', 'Mohan', '250.5'],
        ['102', 'Bob', '150.0'],
        ['103', 'Fatima', '300.75'],
        ['104', 'David', '400.2'],
        ['105', 'Aryan', '330.1']], dtype='<U32'),
 array([['2023-08-01'],
        ['2023-08-02'],
        ['2023-08-01'],
        ['2023-08-03'],
        ['2023-08-04']], dtype='<U32')]

In [19]:
np.vsplit(transactions, [4])

[array([['101', 'Mohan', '250.5', '2023-08-01'],
        ['102', 'Bob', '150.0', '2023-08-02'],
        ['103', 'Fatima', '300.75', '2023-08-01'],
        ['104', 'David', '400.2', '2023-08-03']], dtype='<U32'),
 array([['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')]

### Boolean operations

In [20]:
monthly_sales = np.array([30, 33, 35, 28, 42])

result = monthly_sales < 32
result

array([ True, False, False,  True, False])

In [21]:
monthly_sales[result]

array([30, 28])

In [22]:
monthly_sales[result] = -1
monthly_sales

array([-1, 33, 35, -1, 42])

### Argmax

In [23]:
index = np.argmax(monthly_sales)
index

np.int64(4)

In [24]:
monthly_sales[4]

np.int64(42)

#### Now print a transaction with a maximum amount

In [25]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [26]:
transactions[:,2]

array(['250.5', '150.0', '300.75', '400.2', '330.1'], dtype='<U32')

In [27]:
transactions[:,2].astype(float)

array([250.5 , 150.  , 300.75, 400.2 , 330.1 ])

In [28]:
t_index = np.argmax(transactions[:,2].astype(float))
t_index

np.int64(3)

In [29]:
transactions[t_index]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [30]:
transactions[transactions[:,0]=="101"]

array([['101', 'Mohan', '250.5', '2023-08-01']], dtype='<U32')